name: build-cronify

on:
  workflow_dispatch: {}

jobs:
  build:
    strategy:
      matrix:
        include:
          # =====================
          # LINUX
          # =====================
          - os: ubuntu-24.04
            name: linux-x64
            outfile: cronify-linux-x64

          - os: ubuntu-24.04-arm
            name: linux-arm64
            outfile: cronify-linux-arm64

          # =====================
          # MACOS
          # =====================
          - os: macos-14
            name: macos-arm64
            outfile: cronify-macos-arm64

          - os: macos-13
            name: macos-x64
            outfile: cronify-macos-x64

          # =====================
          # WINDOWS
          # =====================
          - os: windows-2022
            name: windows-x64
            outfile: cronify-windows-x64.exe

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install

      - name: Build frontend
        working-directory: frontend
        run: |
          bun install
          bun run build

      - name: Build binary
        run: bun build ./index.ts --compile --outfile ./dist/${{ matrix.outfile }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.name }}
          path: dist/${{ matrix.outfile }}
